groups:
- name: relativistic-alerts
  rules:
  - alert: HighErrorRate
    expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.1
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "High error rate detected"
      description: "Error rate is {{ $value }} per second"

  - alert: HighLatency
    expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 1
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High latency detected"
      description: "95th percentile latency is {{ $value }} seconds"

  - alert: ServiceDown
    expr: up == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Service {{ $labels.instance }} is down"
      description: "Service has been down for more than 1 minute"

  - alert: HighMemoryUsage
    expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes > 0.9
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High memory usage on {{ $labels.instance }}"
      description: "Memory usage is at {{ $value | humanizePercentage }}"

  - alert: HighCPUUsage
    expr: rate(process_cpu_seconds_total[5m]) > 0.8
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High CPU usage on {{ $labels.instance }}"
      description: "CPU usage is at {{ $value | humanizePercentage }}"

  - alert: NodeUnreachable
    expr: relativistic_node_health_status == 0
    for: 2m
    labels:
      severity: critical
    annotations:
      summary: "Node {{ $labels.node_id }} is unreachable"
      description: "Node has been unreachable for more than 2 minutes"

  - alert: NetworkPartition
    expr: relativistic_network_connectivity < 0.5
    for: 3m
    labels:
      severity: critical
    annotations:
      summary: "Network partition detected"
      description: "Network connectivity is at {{ $value | humanizePercentage }}"

  - alert: ConsensusDegraded
    expr: relativistic_consensus_health_status == 0
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: "Consensus system degraded"
      description: "Consensus system health check failed"

  - alert: PropagationDelayHigh
    expr: relativistic_propagation_delay_seconds > 10
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High propagation delay detected"
      description: "Propagation delay is {{ $value }} seconds"

  - alert: ValidationFailureRateHigh
    expr: rate(relativistic_validation_failures_total[5m]) > 0.05
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High validation failure rate"
      description: "Validation failure rate is {{ $value }} per second"