server:
  address: ":8080"
  environment: "production"
  log_level: "info"
  cors_allowed_origins:
    - "https://relativistic.example.com"
    - "https://api.relativistic.example.com"
  shutdown_timeout: "30s"

database:
  host: "relativistic-postgresql"
  port: 5432
  name: "relativistic"
  username: "relativistic_user"
  password: "${POSTGRES_PASSWORD}"
  ssl_mode: "require"
  max_connections: 100
  max_idle_connections: 20
  connection_timeout: "30s"

cache:
  host: "relativistic-redis"
  port: 6379
  password: "${REDIS_PASSWORD}"
  db: 0
  pool_size: 200
  read_timeout: "3s"
  write_timeout: "3s"

security:
  jwt_secret: "${JWT_SECRET}"
  jwt_expiry: "24h"
  api_key: "${API_KEY}"
  rate_limit: 10000
  cors_enabled: true

monitoring:
  prometheus:
    enabled: true
    path: "/metrics"
  health_check:
    enabled: true
    interval: "30s"
  metrics_collection_interval: "10s"

network:
  node_registration:
    auto_approve: true
    max_nodes: 10000
  propagation:
    max_calculation_time: "10s"
    batch_size: 500
  discovery:
    enabled: true
    interval: "30s"

relativistic:
  speed_of_light: 299792458
  earth_radius: 6371000
  max_interplanetary_distance: 400000000000
  time_dilation_factor: 1.0
  validation_confidence_threshold: 0.8

logging:
  level: "info"
  format: "json"
  output: "/var/log/relativistic/app.log"
  rotation:
    enabled: true
    max_size: 500
    max_backups: 30
    max_age: 90