server:
  address: ":8080"
  environment: "development"
  log_level: "debug"
  cors_allowed_origins:
    - "*"
  shutdown_timeout: "30s"

database:
  host: "localhost"
  port: 5432
  name: "relativistic"
  username: "postgres"
  password: "password"
  ssl_mode: "disable"
  max_connections: 50
  max_idle_connections: 10
  connection_timeout: "30s"

cache:
  host: "localhost"
  port: 6379
  password: ""
  db: 0
  pool_size: 100
  read_timeout: "3s"
  write_timeout: "3s"

security:
  jwt_secret: "development-secret-change-in-production"
  jwt_expiry: "24h"
  api_key: "dev-api-key"
  rate_limit: 1000
  cors_enabled: true

monitoring:
  prometheus:
    enabled: true
    path: "/metrics"
  health_check:
    enabled: true
    interval: "30s"
  metrics_collection_interval: "15s"

network:
  node_registration:
    auto_approve: true
    max_nodes: 1000
  propagation:
    max_calculation_time: "5s"
    batch_size: 100
  discovery:
    enabled: true
    interval: "60s"

relativistic:
  speed_of_light: 299792458
  earth_radius: 6371000
  max_interplanetary_distance: 400000000000
  time_dilation_factor: 1.0
  validation_confidence_threshold: 0.7

logging:
  level: "debug"
  format: "json"
  output: "stdout"
  rotation:
    enabled: true
    max_size: 100
    max_backups: 10
    max_age: 30